# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Afterburner' do
pod 'SVHTTPRequest', :head

end

target 'AfterburnerTests' do

end

